Database:
  Host: localhost
  Port: 5432
  Name: dominion
  User: dominion
  Pass: dominion

AutoCreateRadius: 10
MaxX: 128
MaxY: 64
MaxZ: 128

AutoClean:
  Enabled: false
  AfterDays: 180

BlueMap: true

Debug: false