Database:
  Type: sqlite # pgsql, sqlite
  Host: localhost
  Port: 5432
  Name: dominion
  User: dominion
  Pass: dominion

# 自动圈地大小
AutoCreateRadius: 10  #-1 表示不开启

# -1 表示不限制
Limit:
  MinY: -64     # 最小Y坐标
  MaxY: 320     # 最大Y坐标
  SizeX: 128    # X方向最大长度
  SizeY: 64     # Y方向最大长度
  SizeZ: 128    # Z方向最大长度
  Amount: 10    # 最大领地数量
  Depth: 3      # 子领地深度 0：不允许子领地 -1：不限制
  WorldBlackList: []  # 不允许领地的世界

Teleport:
  Enable: true
  # 传送延迟 秒
  Delay: 0
  # 冷却时间 秒
  CoolDown: 0

# 自动清理长时间未上线玩家的领地
AutoCleanAfterDays: 180 # -1 表示不开启

# 圈地工具
Tool: ARROW

# 经济系统 - 需要安装Vault插件
Economy:
  Enable: false
  # 单价 - 每方块
  Price: 10.0
  # 是否只计算xz平面积
  OnlyXZ: false
  # 删除领地退还比例
  Refund: 0.85

BlueMap: true

CheckUpdate: true

Debug: false