name: Dominion
version: '${project.version}'
main: cn.lunadeer.dominion.Dominion
api-version: '1.20'
load: STARTUP
folia-supported: true
loadbefore:
  - Vault
commands:
  Dominion:
    description: 领地插件命令
    usage: /dominion <cmd>
    aliases: [dominion, dom]